---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: "Pull Request: Validate"

on:
  pull_request:
    branches: ["main"]
    types: ["opened", "synchronize", "reopened"]

concurrency:
  group: ${{ github.head_ref }}-pr-validate
  cancel-in-progress: true

jobs:
  simple-checks:
    uses: Mistikan/docker-images/.github/workflows/simple-checks.yaml@main

  get-changed-images:
    uses: Mistikan/docker-images/.github/workflows/get-changed-images.yaml@main

  build-images:
    needs: ["simple-checks", "get-changed-images"]
    if: ${{ needs.get-changed-images.outputs.addedOrModified == 'true' }}
    uses: Mistikan/docker-images/.github/workflows/build-images.yaml@main
    secrets: inherit
    with:
      appsToBuild: "${{ needs.get-changed-images.outputs.addedOrModifiedImages }}"
      pushImages: false
      sendNotifications: false
